language: cpp
before_install:
  # Install dependencies
  - sudo apt-get update
  - sudo apt-get -y install build-essential zlib1g-dev curl libluajit-5.1-dev
  
  # Download and install automake-1.13.1, required for SDL
  - curl "http://ftp.gnu.org/gnu/automake/automake-1.13.1.tar.gz" > automake-1.13.1.tar.gz
  - tar -zxvf automake-1.13.1.tar.gz
  - (cd automake-1.13.1 && ./configure && make -j5 && sudo make install)
  
  #SDL2
  - hg clone http://hg.libsdl.org/SDL && mkdir SDL_build
  - (cd SDL && ./autogen.sh)
  - (cd SDL_build && ../SDL/configure && make -j5 && sudo make install)
  
  #SDL2_image
  - hg clone http://hg.libsdl.org/SDL_image
  - (cd SDL_image && ./autogen.sh)
  - (cd SDL_image && ./configure && make -j5 && sudo make install)
  
  #SDL2_mixer
  - hg clone http://hg.libsdl.org/SDL_mixer
  - (cd SDL_mixer && ./autogen.sh)  
  - (cd SDL_mixer && ./configure && make -j5 && sudo make install)

script:
  - make all -j5
  - (mkdir cmakebuild && cd cmakebuild && cmake -DTRAVIS_BUILD=1 .. && make -j5)

notifications:
  webhooks: http://n.tkte.ch/h/421/D6ZQTEJ8lFTwTw9_0vSDL-dX
