before_install:
  - git submodule init
  - git submodule update
  - sudo apt-get -y -qq install build-essential zlib1g-dev
  - mkdir dummyprefix
  - export PREFIX=$PWD/dummyprefix
  - hg clone http://hg.libsdl.org/SDL && mkdir SDL_build
  - (cd SDL_build && ../SDL/configure --prefix=$PREFIX && make -j5 && make install)
  - hg clone http://hg.libsdl.org/SDL_image
  - (cd SDL_image && ./configure --prefix=$PREFIX && make -j5 && make install)
  - hg clone http://hg.libsdl.org/SDL_mixer
  - (cd SDL_mixer && ./configure --prefix=$PREFIX && make -j5 && make install)

script:
  - make install
